network:
  namespace: default
Service:
  nodePort: 30030
frontend:
  replicas: 1
  metadata:
    name: guestbookapp-v6
    labels: 
      tier: frontend
      version: gesamte-Version-v6

  selector:
    matchLabels:
      app: guestbook_app
  
  containers:
    name: guestbook
    image:
      name: 172.17.0.1:5000/v6-nhe
      tag: latest

    resources:
      requests:
        cpu: 0.25
        memory: 500Mi
      limits:
        cpu: 0.5
        memory: 1Gi

    env:
      name1: Guestbook
      value1: Das ist die Guestbook version mit allen Aufträgen in einem.
      name2: Status
      value2: Die Enviroment Variable funktioniert 
      valueFrom:
        secretKeyRef:
          name: secret-guestbook
          key: SecretEnv
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 3

    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10  

    startupProbe:
      failureThreshold: 15
      periodSeconds: 10

    volumeMounts:
      name: html
      readOnly: true

    volumes:
      name: html
      configMap:
        name: html-configmap

    initContainers:
      name: redis-test
      image:
        name: redis:alpine
      command: ['sh', '-c', 'redis-cli -h redis-leader -p 6379 ping | grep PONG']

leader:
  name: redis-leader
  replicas: 1
  containers:
    name: redis-dumps
    command: ["/bin/sh", "-c"] 
    args: [while true; do sleep 60; redis-cli -h redis-leader -p 6379 SAVE; done]

follower:
  name: redis-follower

serviceAccounts:
  creationTimestamp: null
  backend:
    label: backend
    name: backendsa

  frontend:
    label: frontend
    name: serviceaccountgb

secret:
  name: secret-guestbook
  secretEnv: RGllc2UgVmFyaWFiZWwgc3RhbW10IHZvbiBlaW5lbSBTZWNyZXQ=

configMap:
  name: html-configmap
  data:
    html: | 
      <html ng-app="redis">
          <head>
            <title>Guestbook</title>
            <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js"></script>
            <script src="controllers.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.6/ui-bootstrap-tpls.js"></script>
          </head>
          <body ng-controller="RedisCtrl">
            <div style="width: 50%; margin-left: 20px">
              <h2>Guestbook</h2>
            <form>
            <fieldset>
            <input ng-model="msg" placeholder="Messages" class="form-control" type="text" name="input"><br>
            <button type="button" class="btn btn-primary" ng-click="controller.onRedis()">Submit</button>
            </fieldset>
            </form>
            <div>
              <div ng-repeat="msg in messages track by $index">
                {{ "{{" }} msg {{ "}}" }}
              </div>
            </div>
            </div>
          </body>
          </html> 

cronJob:
  name: dbsize
  schedule: "* */1 * * *"
  containers:
    command: ["sh", "-c", "redis-cli -h redis-leader -p 6379 MEMORY STATS"]
  restart: Never

      



