apiVersion: v1
kind: Pod
metadata:
  name: non-root
  labels: 
    tier: frontend
    app: guestbook
spec:
  containers:
  - name: pod-auftrag10
  # Anderes Nginx image, damit man es mit runAsNonRoot laufen kann.
    image: nginxinc/nginx-unprivileged 
    ports:
    - containerPort: 8080
    securityContext:
      runAsNonRoot: true
      # 2.Teil, Damit werden alle Capabilities entfernt.
      capabilities:
        drop: ["ALL"] 
