apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: guestbook
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: localhost:5000/v5-nhe
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.25 
            memory: 500Mi
          limits:
            cpu: 0.5
            memory: 1Gi
            
      - name: stresstest
        image: busybox
        command: ["tail", "/dev/zero"]
      serviceAccountName: frontend-sa