apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: guestbook
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: 172.17.0.1:5000/v5-nhe
        ports:
        - containerPort: 80
      tolerations:
      - key: "tier"
        operator: "Equal"
        value: "frontend"
        effect: "NoSchedule"