apiVersion: v1
kind: Secret
metadata:
  name: secret-auftrag8
data:
  index.html: |
    PGh0bWwgbmctYXBwPSJyZWRpcyI+CiAgICA8aGVhZD4KICAgICAgPHRpdGxlPkd1ZXN0Ym9vazwvdGl0bGU+CiAgICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iLy9uZXRkbmEuYm9vdHN0cmFwY2RuLmNvbS9ib290c3RyYXAvMy4xLjEvY3NzL2Jvb3RzdHJhcC5taW4uY3NzIj4KICAgICAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vYWpheC5nb29nbGVhcGlzLmNvbS9hamF4L2xpYnMvYW5ndWxhcmpzLzEuMi4xMi9hbmd1bGFyLm1pbi5qcyI+PC9zY3JpcHQ+CiAgICAgIDxzY3JpcHQgc3JjPSJjb250cm9sbGVycy5qcyI+PC9zY3JpcHQ+CiAgICAgIDxzY3JpcHQgc3JjPSJodHRwczovL2NkbmpzLmNsb3VkZmxhcmUuY29tL2FqYXgvbGlicy9hbmd1bGFyLXVpLWJvb3RzdHJhcC8yLjUuNi91aS1ib290c3RyYXAtdHBscy5qcyI+PC9zY3JpcHQ+CiAgICA8L2hlYWQ+CiAgICA8Ym9keSBuZy1jb250cm9sbGVyPSJSZWRpc0N0cmwiPgogICAgICA8ZGl2IHN0eWxlPSJ3aWR0aDogNTAlOyBtYXJnaW4tbGVmdDogMjBweCI+CiAgICAgICAgPGgyPkd1ZXN0Ym9vazwvaDI+CiAgICAgIDxmb3JtPgogICAgICA8ZmllbGRzZXQ+CiAgICAgIDxpbnB1dCBuZy1tb2RlbD0ibXNnIiBwbGFjZWhvbGRlcj0iTWVzc2FnZXMiIGNsYXNzPSJmb3JtLWNvbnRyb2wiIHR5cGU9InRleHQiIG5hbWU9ImlucHV0Ij48YnI+CiAgICAgIDxidXR0b24gdHlwZT0iYnV0dG9uIiBjbGFzcz0iYnRuIGJ0bi1wcmltYXJ5IiBuZy1jbGljaz0iY29udHJvbGxlci5vblJlZGlzKCkiPlN1Ym1pdDwvYnV0dG9uPgogICAgICA8L2ZpZWxkc2V0PgogICAgICA8L2Zvcm0+CiAgICAgIDxkaXY+CiAgICAgICAgPGRpdiBuZy1yZXBlYXQ9Im1zZyBpbiBtZXNzYWdlcyB0cmFjayBieSAkaW5kZXgiPgogICAgICAgICAge3ttc2d9fQogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L2JvZHk+CiAgICA8L2h0bWw+


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auftrag8-deployment
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: guestbook_configmap
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook_configmap
    spec:
      containers:
      - name: pod-auftrag2
        image: localhost:5000/v5-nhe
        ports:
        - containerPort: 80
        # Auftrag 8 mounten von Secret
        volumeMounts:
        - name: html
          mountPath: /var/www/html
      volumes:
      - name: html
        secret:
          secretName: html-secret