apiVersion: ENC[AES256_GCM,data:6XQ=,iv:h8E/Yvlig2wVhfJMcy7ASTpp8QZwUHPK3HhvqTFsOSc=,tag:/J0H7cWFDV55di4NHnTrrg==,type:str]
kind: ENC[AES256_GCM,data:Hsq+y+I+,iv:/gDdR66i+eRqQkiAijBwMnPofYAYaqOegTWM08IsM/Q=,tag:NRr4sA3GtrCD9NxFyZShYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:22MD2M67ka1j9ChEtaSL8hdfsQuU,iv:fz4f+3vFr3TD5Goi2o+SlPZ+fRrsmnbptvowyUnhIXY=,tag:TqjUbzlorWFDXTqsJPC4fw==,type:str]
    namespace: ENC[AES256_GCM,data:nMwsiI5w7Q==,iv:Y++O3sd6S4C+o6nAmCyaiFa5pAJHZGqFHAdG5vft19M=,tag:HufKyFuoi3yN8MpcBmYWbA==,type:str]
data:
    username: ENC[AES256_GCM,data:h9wXi+1hwBo=,iv:tPl23tJ+nhDW7KkLHum+bqOxgxCCqvjoR055sqjlOK4=,tag:NZhhzNE2DNoI7L3n69AMnw==,type:str]
    password: ENC[AES256_GCM,data:ZYHuMBI39eQsFKeO,iv:a3QmiiwtVRI5/wjLFE1IDXP0sZe63NVc3uUnZ+jhLbs=,tag:0yjn5klNff8PynFIg7KIeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-23T09:46:41Z"
    mac: ENC[AES256_GCM,data:DN9yHg5lfmuHeF9mQayQe/VcO9ivDl2FGe/cAMCcdhzSPEnIo/oEaxEtDi3idex5DzGL9EbMXsmyKbcUOR+IBhjcILYd7v3DgckTbZYyNOBaerVdetAzHHC817QSVvsQKYoY0z2IvwIRq+8LBcVGZczy/cGP9BcBi1RYG5hNe1k=,iv:iB5shGk7CyqOFJ6lp5cji8oNBqsPhuR00X87UPjP4Ug=,tag:oGkomiwTf0XlRD2ezp2ipQ==,type:str]
    pgp:
        - created_at: "2024-08-23T09:46:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8TbMrXFfwpWAQ/8DSJkEXK6QC30rR3YtmT02QESbdPzNhpaCno1u2QLi/sW
            M6RZMD5XnEoe3tNwCMQOhJIxSeFj2C+3JfD2maB7RE06htQFtFqRbKE7WnYSiWYZ
            DpQVbmXScn2UjA5YRZ+AzSbsPyCmI8hRUDbg7l8veZcxqcPZVYtWpi5YfJ5tffcu
            FIdwMCUziWkB3qJrcU/c5suQKzR2vdv5F0vTaiZ0tJAemTi7VDqvGqco+6E2x8Uc
            nz2LeICoLoCLyBgC6yYm/tjCTFH9DDWVYGBF5kiyP/w4ZLpEN8Y3dX+lirCUx6hE
            2QXQXiA6aaXkA2/rYLhaoPZD7CBnFK0a9e6OCqN68uMj3giJlseu1uSPJd+V0yjC
            qRl/+bYdhpLuhsPFdIyh3U8+7WYIPXUC3ecvcPg/ELzkjHlLsB5ACuubv1cOhg5W
            Px1Jz7nCqun7Erp3ZUs2u8Hmk/+iJlOPDPiuk8O7/fhpqFhMP3J8Gc2VT80dGLUh
            d5NDMnGRFJNuWAkhECY9nj09eIViGQq97zo2rEpoBugjv9ToWObxUH6xikljw/8I
            B4iL+tyfX7HCdhdY0yg0CrcuuoKjStUiPMJgjHdKSPFaoobxKMQrnXsePJd5bn1z
            as/lSOM3qc/PgqNLuOZh+lDqz6Exk7NGXty7aq0KGgrn6klCAEMvMpgreJD4Fb/U
            ZgEJAhByknJQOPMJw+/NULGIUUN9PCH4KzWvd2Owbst63DAqfnHhSkrqwkc6Wtcj
            heA8yNGZlvp9wUEPxya2M7k0+TVv4/hZnTrJDhfjQEXSRbx8Ou4qLT96mh9YVM2J
            5BucJ6RB3A==
            =0tii
            -----END PGP MESSAGE-----
          fp: DD4587DB3C47FCD2F7E73AE543B46593741AA88B
    unencrypted_suffix: _unencrypted
    version: 3.9.0
