apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html ng-app="redis">
    <head>
      <title>Guestbook</title>
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js"></script>
      <script src="controllers.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.6/ui-bootstrap-tpls.js"></script>
    </head>
    <body ng-controller="RedisCtrl">
      <div style="width: 50%; margin-left: 20px">
        <h2>Guestbook</h2>
      <form>
      <fieldset>
      <input ng-model="msg" placeholder="Messages" class="form-control" type="text" name="input"><br>
      <button type="button" class="btn btn-primary" ng-click="controller.onRedis()">Submit</button>
      </fieldset>
      </form>
      <div>
        <div ng-repeat="msg in messages track by $index">
          {{msg}}
        </div>
      </div>
      </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auftrag2-replicaset
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: pod-auftrag2
        image: localhost:5000/v5-nhe
        ports:
        - containerPort: 80
          
        # Auftrag 6 Enviroment Variables hinzufügen
        env:
        - name: DEMO_ENV
          value: "Es hat funktioniert"
        - name: TEST
          value: "true"

        # Auftrag 7 Config Map Mount
        volumeMounts:
        - name: html
          mountPath: /var/www/html
          readOnly: false
      volumes:
      - name: html
        configMap:
          name: html-configmap

