apiVersion: v1
kind: Pod
metadata:
  name: dropcap
  labels: 
    tier: frontend
    app: guestbook
spec:
  containers:
  - name: pod-auftrag10
    image: nginxinc/nginx-unprivileged
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        drop: ["ALL"]