apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
      app: guestbook
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook
    spec:
      affinity:   
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane # Label vom Controle-Plane
                operator: NotIn  # Pods werden nicht auf einem Node mit diesem Label platziert.
                values: 
                - "true"
      containers:
      - name: guestbook
        image: 172.17.0.1:5000/v5-nhe
        ports:
        - containerPort: 80