apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbsize
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbsize
            image: redis:alpine
            command: ["sh", "-c", "redis-cli -h redis-service -p 6379 MEMORY STATS"]
          restartPolicy: Never