##############################
#    Redis Leader Service    #
##############################

# Service f체r redis-leader
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
spec:
  selector:
    app: redis-leader
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  labels:
    app: redis-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-leader
  template:
    metadata:
      labels:
        app: redis-leader
    spec:
      serviceAccountName: backendsa # Service Account hinzuf체gen
      containers:
      - name: redis-leader
        image: docker.io/redis:6.0.5
        ports:
        - containerPort: 6379

      - name: redis-dumps
        image: redis
        command: ["/bin/sh", "-c"]     # Startet eine Shell und gibt die n채chfolgenden Befehle dort ein.
        # Hier wird alle 60 Sekunden ein Backup erstellt vom Redis-Leader Container
        args:             
        - >
          while true; do
            sleep 60;  # Zeit zwischen den Dumps
            redis-cli -h redis-leader -p 6379 SAVE;  # Erstellt einen Dump auf dem Redis-Leader Container
          done




##############################
#   Redis Follower Service   #
##############################
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
spec:
  selector:
    app: redis-follower
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  labels:
    app: redis-follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-follower
  template:
    metadata:
      labels:
        app: redis-follower
    spec:
      serviceAccountName: backendsa # Service Account hinzuf체gen
      containers:
      - name: redis-follower
        image: gcr.io/google_samples/gb-redis-follower:v2
        ports:
        - containerPort: 6379