apiVersion: v1
kind: Service
metadata:
  name: frontend-service-v5
spec:
  selector:
    app: guestbook_app
    version: v5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbookapp-v5
  labels:
    version: v5
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook_app
      version: v5
  template:
    metadata:
      labels:
        app: guestbook_app
        version: v5
    spec:
      containers:
      - name: guestbook 
        image: 172.17.0.1:5000/v5-nhe:v5.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
spec:
  selector:
    app: redis-leader
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  labels:
    app: redis-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-leader
  template:
    metadata:
      labels:
        app: redis-leader
    spec:
      containers:
      - name: redis-leader
        image: docker.io/redis:6.0.5
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
spec:
  selector:
    app: redis-follower
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  labels:
    app: redis-follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-follower
  template:
    metadata:
      labels:
        app: redis-follower
    spec:
      containers:
      - name: redis-follower
        image: gcr.io/google_samples/gb-redis-follower:v2
        ports:
        - containerPort: 6379 