apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronJob.name }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronJob.name }}
            image: redis:alpine
            command: {{ .Values.cronJob.containers.command }}
          restartPolicy: {{ .Values.cronJob.restart }}