##############################
#    Redis Leader Service    #
##############################

# Service f체r redis-leader
apiVersion: v1
kind: Service
metadata:
  name: redis-leader 
spec:
  selector:
    app: {{ .Values.leader.name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.leader.name }}
  labels:
    app: {{ .Values.leader.name }}
spec:
  replicas: {{ .Values.leader.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.leader.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.leader.name }}
    spec:
      serviceAccountName: backendsa # Service Account hinzuf체gen
      containers:
      - name: {{ .Values.leader.name }}
        image: docker.io/redis:6.0.5
        ports:
        - containerPort: 6379

      - name: {{ .Values.leader.containers.name }}
        image: redis
        command: {{ .Values.leader.containers.command }}    # Startet eine Shell und gibt die n채chfolgenden Befehle dort ein.
        # Hier wird alle 60 Sekunden ein Backup erstellt vom Redis-Leader Container
        args: {{ .Values.leader.containers.args }}


##############################
#   Redis Follower Service   #
##############################
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
spec:
  selector:
    app: redis-follower
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.follower.name }}
  labels:
    app: {{ .Values.follower.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.follower.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.follower.name }}
    spec:
      serviceAccountName: backendsa # Service Account hinzuf체gen
      containers:
      - name: {{ .Values.follower.name }}
        image: gcr.io/google_samples/gb-redis-follower:v2
        ports:
        - containerPort: 6379