apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tier: {{ .Values.serviceAccounts.frontend.label}}  # SA für Frontend
  creationTimestamp: {{ .Values.serviceAccounts.createionTimestamp }}
  name: {{ .Values.serviceAccounts.frontend.name }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tier: {{ .Values.serviceAccounts.backend.label }} # SA für Backend
  creationTimestamp: {{ .Values.serviceAccounts.createionTimestamp }}
  name: {{ .Values.serviceAccounts.backend.name }}


